#!/bin/sh

# ObliviousGmn, April 2015
# https://github.com/ObliviousGmn
# Header for my Terminal.. 

. Colors

RN="$(whoami | sed -e 's/\b\(.\)/\u\1/g')"
RS="87"
US="85"

if [ $(id -u) -eq 0 ];
then
	printf " ${Green}${RN} %${RS}s $(date +%I:%M)${Reset} \n"
else
	printf " ${Green}$(hostname) %${US}s $(date +%I:%M)${Reset} \n"
fi

